title: Zetong Liu
author:
  name: 
  email: 
# description: .
theme: minima
header_pages:
  - about.md
  - books.md

  # social_links:
  #  - title: my GitHub
  #    icon: github
  #    url: "https://github.com/ZetongLiu"
  #  - title: my linkedin
  #    icon: linkedin
  #    url: "https://www.linkedin.com/in/zetong-liu-113627215/"

